config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "up" => "rails/health#show", as: :rails_health_check

  root "tanks#index"
  post '/tanks', to: 'tanks#create', as: 'create_tank'
  resources :tanks do
    resources :fish
    member do
      post 'feed'
      post 'add_plant'
      post 'bubble'
      post 'plant_action'
      post 'add_lamp'
      post 'increase_tank_size'
      post 'new_day'
      post 'reset_all'
      get 'details_death'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/fish.rb
class Fish < ApplicationRecord
  belongs_to :tank
  validates :name, presence: true
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :tank
end

app/models/tank.rb
class Tank < ApplicationRecord
  belongs_to :user
  has_many :fish, dependent: :destroy
  has_many :plants, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tanks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def default_url_options
    { host: ENV['DOMAIN'] || 'localhost:3000' }
  end
end

app/controllers/fish_controller.rb
class FishController < ApplicationController
  def new
    @tank = Tank.find(params[:tank_id])
    @fish = Fish.new
  end

  def create
    @tank = Tank.find(params[:tank_id])
    @fish = Fish.new(fish_params)
    @fish.tank = @tank
      if @fish.save
        redirect_to tank_path(@tank, rules: true)
      else
        render :new, status: :unprocessable_entity
      end
  end

  private

  def fish_params
    params.require(:fish).permit(:name)
  end
end

app/controllers/tanks_controller.rb
class TanksController < ApplicationController
  before_action :set_tank, only: %i[reset_all show feed add_lamp add_plant increase_tank_size new_day details_death]
  before_action :set_user, only: %i[index show]
  before_action :authenticate_user!

  CONFIG = {
    plant_price: 5,
    fish_growth: 1,
    food_nitrate_increase: 0.8,
    plant_nitrate_decrease: 1,
    lamp_price: 20,
    tank_increase_price: 10,
    tank_increase_liters: 10,
    win_bubble_amount: 20
  }.freeze

  # controller actions

  def index
    @tanks = @user.tanks.reload
    @tanks = @user.tanks.joins(:fish).where(fish: { alive: true }).distinct
  end

  def show; end

  def new
    @tank = Tank.new
  end

  def create
    @user = current_user
    @tank = Tank.new
    @tank.user = @user
    @tank.save
    redirect_to new_tank_fish_path(@tank)
  end

  # user actions

  def reset_all
    reset_tank
    redirect_to tank_path(@tank)
  end

  def feed
    @tank.fish.each do |f|
      f.size += CONFIG[:fish_growth] if f.size < 20
      f.fed = true
      f.save
      @tank.nitrate += f.size * CONFIG[:food_nitrate_increase]
    end
      @tank.save
      redirect_to tank_path(@tank)
  end

  def add_plant
    if (@tank.liters - (@tank.plants.count * 2)) >= 2
      buy_plant
    else
      flash[alert:] = "Il n'y a pas assez d'eau pour ajouter une plante"
    end
    redirect_to tank_path(@tank)
  end

  def add_lamp
    if spend_bubble(CONFIG[:lamp_price]) == 'paid' && @tank.has_lamp == false
      @tank.has_lamp = true
      @tank.save
    end
    redirect_to tank_path(@tank)
  end

  def lamp_broken
    set_tank
    if rand(1..10) <= 3 # 30% chance of lamp breaking
      @tank.has_lamp = false
      @tank.save
    end
    redirect_to tank_path(@tank)
  end


  def increase_tank_size
    if spend_bubble(CONFIG[:tank_increase_price]) == 'paid'
      @tank.liters += CONFIG[:tank_increase_liters]
      @tank.save
    end
    redirect_to tank_path(@tank)
  end

  def new_day
    if @tank.fish.last.fed?
      plant_action
      if @tank.nitrate >= @tank.liters
        rip
      else
        fish_sick
        fish_get_hungry
        @tank.has_lamp ? lamp_action : plant_life
        win_bubble(CONFIG[:win_bubble_amount] * @tank.fish.count)
        @tank.age += 1
        @tank.save
      end
      redirect_to tank_path(@tank, bubble: CONFIG[:win_bubble_amount], to_day: true)
    else
      redirect_to tank_path(@tank), alert: "Nourris le poisson pour passer au jour suivant."
    end
  end

  def details_death
  end

  private

  def spend_bubble(amount)
    set_tank
    set_user
    if (@user.currency - amount) >= 0
      @user.currency -= amount
      @user.save
      'paid'
    else
      flash[:alert] = "Tu n'as pas assez de bubulles"
    end
  end

  def set_tank
    @tank = Tank.find(params[:id])
  end

  def set_user
    @user = current_user
  end

  def win_bubble(amount)
    set_user
    @user.currency += amount
    @user.save
  end


  def plant_action
    set_tank
    @tank.nitrate -= (@tank.plants.count * CONFIG[:plant_nitrate_decrease])
    @tank.nitrate = 0 if @tank.nitrate.negative?
    @tank.save
  end

  def lamp_action
    set_tank
    @tank.plants.each do |p|
      p.life_expectancy = nil
      p.save
    end
  end

  def plant_life
    set_tank
    @tank.plants.each do |p|
      p.life_expectancy.zero? ? p.destroy : p.life_expectancy -= 1
      p.save
    end
  end

  def rip
    set_tank
    set_user
    @tank.fish.each do |f|
      f.alive = false
      f.save
    end
    @user.currency = 0
    @user.save
  end

  def fish_sick
    set_tank
    @condition = @tank.nitrate.to_f / @tank.liters
    @tank.fish.each do |f|
      (@condition >= 0.5) && (@condition != 1) ? f.sick = true : f.sick = false
      f.save
    end
  end

  def fish_get_hungry
    set_tank
    @tank.fish.each do |f|
      f.fed = false
      f.save
    end
  end

  def reset_tank
    set_tank
    @tank.liters = 5
    @tank.nitrate = 0
    @tank.age = 1
    @tank.has_lamp = false
    @tank.plants.destroy_all
    @fish_name = @tank.fish.first.name
    @tank.fish.destroy_all
    @fish = Fish.create(name: @fish_name)
    @fish.tank = @tank
    @tank.save
  end

  def buy_plant
    set_tank
    if spend_bubble(CONFIG[:plant_price]) == 'paid'
      @plant = Plant.new
      @plant.tank = @tank
      @plant.save
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/day_helper.rb
module DayHelper
end

app/helpers/fish_helper.rb
module FishHelper
end

app/helpers/meta_tags_helper.rb
# app/helpers/meta_tags_helper.rb
module MetaTagsHelper
def meta_title
  content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
end


def meta_description
  content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
end


def meta_image
  meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
  # little twist to make it work equally with an asset or a url
  meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
end
end

app/helpers/tanks_helper.rb
module TanksHelper
end

app/views/fish/new.html.erb
<div class="navbar" style="justify-content: center">
  <div class="logo">
    <%= link_to tanks_path do %>

      <%= image_tag 'fishu/logo.png', style:"width: 80px;" %>
      <% end %>
</div>
</div>

<div class="screen">

  <div class="bag">
  </div>
  <div class="fishi">
  </div>
</div>


<div class="centerfooter">
  <%= form_with model: @fish, url: tank_fish_index_path(@tank), class:"form-with" do |f| %>
    <%= f.text_field :name, class:'input' %>
    <%= f.submit "Nomme ton poisson", class:'btn-index' %>
  <% end %>
  <%= button_to "logout", destroy_user_session_path, method: :delete  %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag asset_path('icon.png') %>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://kit.fontawesome.com/c79b2f09ef.js" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
     <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable" content="yes">
  <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
   <%= render 'shared/ios_pwa_links' %>
  </head>

  <body data-controller="poop">
    <%= yield %>

    <% flash.each do |type, message| %>
  <div class="alert alert-<%= type %>">
    <%= message %>
  </div>
<% end %>
  </body>
</html>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/tanks/index.html.erb
<div class="navbar">
  <div class="logo">
      <%= image_tag 'fishu/logo.png', style:"width:80px"; %>
  </div>
</div>
<div class="screendisplay">
  <% if @user.tanks.empty? == false %>
    <% @tanks.each do |tank| %>

      <%= link_to tank_path(tank), class:" ligne select" do %>
        <span class="nb"><%=tank.liters%></span>

          litres |
            <span class="nb"><%=tank.fish.count%></span>
            <%if tank.fish.count > 1 %>
              <%if tank.fish.last.sick?%>
                poissons | statut: malades
              <%else%>
                poissons | statut: sains
              <%end%>
            <%else%>
              <%if tank.fish.last.sick?%>
                poisson | statut: malade
              <%else%>
                poisson | statut: sain
              <%end%>
            <%end%>


      <%end %>
    <% end %>
  <% end %>
</div>

<div class=centerfooter>
<%= form_with model: [ Tank.new] do |f| %>
<%= f.submit "Creer mon aquarium", class: "btn-index "%>
<% end %>
</div>

app/views/tanks/show.html.erb
<div class="navbar">
  <div class="logo">
    <%= link_to tanks_path do %>
      <%= image_tag 'fishu/logo.png', style:"width: 80px"; %>
      <% end %>
  </div>
</div>
<div class="screen <%= "to_day" if params[:to_day].present? %>">
  <audio id="popSound" src="<%= image_path("fishu/pop.mp3") %>"></audio>
  <audio id="flushSound" src="<%= image_path("https://res.cloudinary.com/detoat4si/video/upload/v1710273036/v983j86nqrjtvd8w2kqv.mp3") %>"></audio>


        <% @tank.fish.each_with_index do |f, i| %>
          <% if @tank.fish.last.alive? %>
              <% if @tank.liters < 20 %>
                <div class="bowl">
                </div>
                <% row_s = "4" %>
                <% row_e = "8" %>
                <% column_s = "4" %>
                <% column_e = "8" %>
                <% length = "Swim" %>
              <% elsif @tank.liters >= 20 && @tank.liters < 50 %>
                <div class="tank" style="grid-row: 1/-1;grid-column-start: 1;"></div>
                <div class="tank" style="grid-row: 1/-1;grid-column-end: 11; justify-self:right"></div>
                <% row_s = "#{rand(1..8)}" %>
                <% row_e = "#{row_s.to_i + 3}" %>
                <% column_s = "#{rand(2..7)}" %>
                <% column_e = "#{(column_s.to_i + 3)}" %>
                <% length = "Swim2" %>
              <% elsif @tank.liters >= 50 && @tank.liters < 80 %>
               <div class="tank" style="grid-row: 1/-1;grid-column-start: 1;"></div>
                <div class="tank" style="grid-row: 1/-1;grid-column-start: 25;justify-self:right"></div>
                <% row_s = "#{rand(1..8)}" %>
                <% row_e = "#{row_s.to_i + 3}" %>
                <% column_s = "#{rand(2..21)}" %>
                <% column_e = "#{(column_s.to_i + 3)}" %>
                <% length = "Swim3" %>
              <% elsif @tank.liters >= 80 && @tank.liters < 150 %>
               <div class="tank" style="grid-row: 1/-1;grid-column-start: 1;"></div>
                <div class="tank" style="grid-row: 1/-1;grid-column-start: 50;justify-self:right"></div>
                <% row_s = "#{rand(1..8)}" %>
                <% row_e = "#{row_s.to_i + 3}" %>
                <% column_s = "#{rand(2..46)}" %>
                <% column_e = "#{(column_s.to_i + 3)}" %>
                <% length = "Swim4" %>
                <%else %>
                <div class="tank" style="grid-row: 1/-1;grid-column-start: 1;"></div>
                <div class="tank" style="grid-row: 1/-1;grid-column-start: 100;justify-self:right"></div>
                <% row_s = "#{rand(1..8)}" %>
                <% row_e = "#{row_s.to_i + 3}" %>
                <% column_s = "#{rand(2..96)}" %>
                <% column_e = "#{(column_s.to_i + 3)}" %>
                <% length = "Swim4" %>

              <%end %>
              <% position = %w[center left right].sample %>
              <% if (i+1).odd? %>
                <% if @tank.fish.last.sick? %>
                  <% speed = rand(5..6) %>
                  <div class="sick" style="grid-row: <%="#{row_s}/#{row_e}"%>;grid-column: <%="#{column_s}/#{column_e}"%>; background-position:<%="#{position}"%>; animation: <%="#{length} #{speed}s linear infinite"%> "></div>
                  <p class ="name" style="grid-row-start: <%="#{row_s}"%>;grid-column-start: <%="#{column_s}"%>; animation: <%="#{length} #{speed}s linear infinite"%> "><%=f.name%></p>
                <% else %>

                  <% speed = rand(2..4) %>
                  <div class="fishi1" style="grid-row: <%="#{row_s}/#{row_e}"%>;grid-column: <%="#{column_s}/#{column_e}"%>; background-position:<%="#{position}"%>; animation: <%="#{length} #{speed}s linear infinite" %> "></div>
                  <p class ="name" style="grid-row-start: <%="#{row_s}"%>;grid-column-start: <%="#{column_s}"%>; animation: <%="#{length} #{speed}s linear infinite"%> "><%=f.name%></p>
                <% end %>
              <% else %>
                <% if @tank.fish.last.sick? %>
                  <% speed = rand(5..6) %>
                  <div class="sick2" style="grid-row: <%="#{row_s}/#{row_e}"%>;grid-column: <%="#{column_s}/#{column_e}"%>; background-position:<%="#{position}"%>; animation: <%="#{length} #{speed}s linear infinite" %> "></div>
                  <p class ="name" style="grid-row-start: <%="#{row_s}"%>;grid-column-end: <%="#{column_e}"%>; animation: <%="#{length} #{speed}s linear infinite"%> "><%=f.name%></p>
                 <% else %>
                  <% speed = rand(2..4) %>
                  <div class="fishi2" style="grid-row: <%="#{row_s}/#{row_e}"%>;grid-column: <%="#{column_s}/#{column_e}"%>; background-position:<%="#{position}"%>; animation: <%="#{length} #{speed}s linear infinite" %> "></div>
                  <p class ="name" style="grid-row-start: <%="#{row_s}"%>;grid-column-end: <%="#{column_e}"%>; animation: <%="#{length} #{speed}s linear infinite"%> "><%=f.name%></p>
                <% end %>
              <% end %>
              <%@tank.plants.each do |plant| %>
              <% if @tank.liters < 20 %>
                <% row_s = "8" %>
                <% row_e = "10" %>
                <% column_s = "#{rand(4..7)}" %>
                <% column_e = "#{(column_s.to_i + 1)}" %>
              <% elsif @tank.liters >= 20 && @tank.liters < 50%>
                <% row_s = "#{rand(8..10)}" %>
                <% row_e = "11" %>
                <% column_s = "#{rand(1..9)}" %>
                <% column_e = "#{(column_s.to_i + 2)}" %>

              <% elsif @tank.liters >= 50 && @tank.liters < 80%>
                <% row_s = "#{rand(7..10)}" %>
                <% row_e = "11" %>
                <% column_s = "#{rand(1..23)}" %>
                <% column_e = "#{(column_s.to_i + 3)}" %>
              <% elsif @tank.liters >= 80 && @tank.liters < 150%>
                <% row_s = "#{rand(7..10)}" %>
                  <% row_e = "11" %>
                  <% column_s = "#{rand(1..47)}" %>
                  <% column_e = "#{(column_s.to_i + 3)}" %>
              <%else %>
                <% row_s = "#{rand(7..10)}" %>
                <% row_e = "11" %>
                <% column_s = "#{rand(1..97)}" %>
                <% column_e = "#{(column_s.to_i + 3)}" %>
              <%end %>
              <%position = %w[center left right bottom].sample %>

              <div class="plant" style="grid-row: <%="#{row_s}/#{row_e}"%>;grid-column: <%="#{column_s}/#{column_e}"%>; background-position:<%="#{position}"%>"></div>
            <%end%>

            <% if @tank.nitrate > 0 %>
              <% n = @tank.nitrate %>
              <% poops = (1..n).to_a %>
              <% poops.each do |poop| %>
                <% if @tank.liters < 20 %>
                  <% row_s = "#{rand(3..8)}" %>
                  <% row_e = "#{(row_s.to_i + 1)} " %>
                  <%  column_s = "#{rand(3..8)}" %>
                  <%  column_e = "#{(column_s.to_i + 1)}" %>
                <% elsif @tank.liters >= 20 && @tank.liters < 50%>
                  <% row_s = "#{rand(1..10)}" %>
                  <% row_e = "#{(row_s.to_i + 1)} " %>
                  <%  column_s = "#{rand(2..10)}" %>
                  <%  column_e = "#{(column_s.to_i + 1)}" %>
                <% elsif @tank.liters > 50 && @tank.liters < 80%>
                  <% row_s = "#{rand(1..10)}" %>
                  <% row_e = "#{(row_s.to_i + 1)} " %>
                  <% column_s = "#{rand(2..24)}" %>
                  <% column_e = "#{(column_s.to_i + 1)}" %>
                <% elsif @tank.liters > 80 && @tank.liters < 150%>
                  <% row_s = "#{rand(2..10)}" %>
                  <% row_e = "#{(row_s.to_i + 1)} " %>
                  <% column_s = "#{rand(2..49)}" %>
                  <% column_e = "#{(column_s.to_i + 1)}" %>
                  <%else %>
                  <% row_s = "#{rand(1..10)}" %>
                  <% row_e = "#{(row_s.to_i + 1)}" %>
                  <% column_s = "#{rand(2..99)}" %>
                  <% column_e = "#{(column_s.to_i + 1)}" %>
                  <%end %>
                  <%position = %w[center left right bottom].sample %>

                  <div class="poop" style="grid-row: <%="#{row_s}/#{row_e}"%>;grid-column: <%="#{column_s}/#{column_e}"%>; background-position:<%="#{position}"%>"></div>

                <% end %>
            <% end %>
          <% else %>

            <%=link_to details_death_tank_path(@tank), style:"grid-column: 4/8;grid-row: 6/11" do %>
              <div class="tomb">
              <div class="causeofdeath" style="grid-row: 4/5;"> </div>
              <div class="causeofdeath" style="grid-row: 3/4;"></div>
              <div class="causeofdeath" style="grid-row: 2/3;"></div>

              </div>
              <% end %>
          <% end %>
        <% end %>





    <%# data-controller="poop" %>

  </div>

<div class="buttons" data-controller="button">
  <div class="set-up">
    <div class="eat-button">
      <%= button_to feed_tank_path(@tank),
                    class:"btn",
                    data: {
                      action: "click->poop#playPopSound"
                    } do %>
        <%= image_tag "fishu/food.png", class:"btn-img" %>
      <% end %>
    </div>

    <div class="button-plant">
      <%= button_to add_plant_tank_path(@tank), class:"btn" do %>
        <%= image_tag "fishu/leaf.png", class:"btn-img" %>
      <%end %>
    </div>

    <div class="lamp-button">
      <% if @tank.has_lamp %>
        <div class="has-lamp"></div>
      <% end %>
      <%= button_to add_lamp_tank_path(@tank), class:"btn" do %>
        <%= image_tag "fishu/bulb.png", class:"btn-img" %>
      <% end %>
    </div>

    <div class="size-button">
      <%= button_to increase_tank_size_tank_path(@tank), class:"btn" do %>
        <%= image_tag "fishu/drop.png", class:"btn-img" %>
      <% end %>
    </div>

      <% if @tank.liters >= 20 %>
    <div class="btn">
        <%= link_to new_tank_fish_path(@tank) do %>
          <div>
          <%= image_tag "fishu/morefish.png", class:"btn-img", style:"width:40px" %>
          <% end %>
          </div>
    </div>
    <% if @tank.liters >= 20 %>
      <% end %>
      <%end %>
  </div>

  <div class="dashboard">
    <div class="bulle">
      <p class="points"><%= @user.currency %>
      <span><%= image_tag 'fishu/bulles.png' %></span>
      </p>
      <% if params[:bubble].present? %>
        <span class="new-points">+ <%= params[:bubble] %></span>
      <% end %>
    </div>
      <%if @tank.fish.count == 1 %>
      <% poisson = "poisson" %>
      <%else %>
      <% poisson = "poissons" %>
      <%end %>

      <span class="underline"> <%= poisson %> </span>
        <% @tank.fish.each do |fish| %>
          <span class="item-fish">
            <%=fish.name%>
            <div class="size"><div class="nb"><%=fish.size%></div>cm
            </div>
          </span>
        <% end %>

        <span class="underline">
          Parametres
        </span>
          <div class="item">
              Plantes : <span class="nb"><%= @tank.plants.count %></span>
          </div>
          <div class="item">
              Lampe : <%= @tank.has_lamp ? "oui" : "on" %>
          </div>

          <div class="item">
            NO3 : <div class="nb"><%= @tank.nitrate %></div>mg/L
          </div>

          <span class="item">
            Volume : <div class="nb"><%= @tank.liters %></div>L
          </span>

          <span class="item">
            Jour : <div class="nb"><%= @tank.age %></div>
          </span>
    </div>



  <div class="day-button" data-controller="night">
  <div style="display: flex; flex-direction: column-reverse;gap: 10px;">
  <% if @tank.fish.last.alive? == false %>
    <div class="">
      <%= button_to reset_all_tank_path(@tank),
      class:"btndroite",
      data: {
        action: "click->button#playFlushSound"
      } do %>
        <%= image_tag "fishu/redo.png", class:"btn-img" %>
      <% end %>
    </div>
  <% end %>
    <a class="btndroite lien" href="#popup" data-turbo="false" class="pop">?</a>
    </div>
    <div class="flex">
    <div class="trous">
    <div class="trou"></div>
    <div class="trou"></div>
    <div class="trou"></div>
    </div>
    <%= button_to new_day_tank_path(@tank), class:"btndroite", data: { action: "#{@tank.fish.last.fed? ? "click->night#nightAnimation" : "click->night#notFed"}" } do %>
      <%= image_tag "fishu/moon.png", class:"btn-img"%>
    <% end %>
    </div>
  </div>
  </div>


  <div class="regles_button">
    <div id="popup" class="regles">
      <div class="regles_content">
        <h1>Règles du jeu</h1>
        <h2>Maintiens ton <%= image_tag "fishu/fishi.png", class:"icon" %> en vie!
          <br>
          <p> * Il a besoin de manger <%= image_tag "fishu/food.png", class:"icon" %> 1 fois par jour <%= image_tag "fishu/moon.png", class:"icon"%></p>
          <p> * Quand il mange <%= image_tag "fishu/food.png", class:"icon" %> il produit du nitrate (NO3-) <%= image_tag "fishu/poop.png", class:"icon" %> </p>
          <p> * Les plantes <%= image_tag "fishu/leaf.png", class:"icon" %> réduisent les nitrates (NO3-) <%= image_tag "fishu/poop.png", class:"icon" %> </p>
          <p> * Les plantes <%= image_tag "fishu/leaf.png", class:"icon" %> ont besoin de lumière <%= image_tag "fishu/bulb.png", class:"icon" %></p>
          <p> * + il mange <%= image_tag "fishu/food.png", class:"icon" %> + il grandit + il a besoin d'espace <%= image_tag "fishu/drop.png", class:"icon" %> </p>
          <p> * Utilise tes bubulles <%= image_tag 'fishu/bulles.png', class:"icon" %> pour faire de nouveaux achats </p>
          <p> * Tu gagnes 20 bubulles <%= image_tag 'fishu/bulles.png', class:"icon" %> par jour <%= image_tag "fishu/moon.png", class:"icon"%> </p>
        <a href="#" class="regles_close" data-turbo="false">&times;</a>
      </div>
    </div>
  </div>